export default [
  [ 4, new String('OPENQASM')],
  [ 2, 2 ],
  [ 6 ],
  [ 4, new String('include')],
  [ 36, new String('"qelib1.inc"')],
  [ 6 ],
  [ 28 ],
  [ 4, new String('q')],
  [ 9 ],
  [ 3, 5 ],
  [ 12 ],
  [ 6 ],
  [ 28 ],
  [ 4, new String('c')],
  [ 9 ],
  [ 3, 5 ],
  [ 12 ],
  [ 6 ],
  [ 4, new String('x')],
  [ 4, new String('q')],
  [ 9 ],
  [ 3, 4 ],
  [ 12 ],
  [ 6 ],
  [ 4, new String('h')],
  [ 4, new String('q')],
  [ 9 ],
  [ 3, 3 ],
  [ 12 ],
  [ 6 ],
  [ 4, new String('h')],
  [ 4, new String('q')],
  [ 9 ],
  [ 3, 4 ],
  [ 12 ],
  [ 6 ],
  [ 4, new String('cx')],
  [ 4, new String('q')],
  [ 9 ],
  [ 3, 3 ],
  [ 12 ],
  [ 7 ],
  [ 4, new String('q')],
  [ 9 ],
  [ 3, 4 ],
  [ 12 ],
  [ 6 ],
  [ 4, new String('h')],
  [ 4, new String('q')],
  [ 9 ],
  [ 3, 3 ],
  [ 12 ],
  [ 6 ],
  [ 32 ],
  [ 4, new String('q')],
  [ 9 ],
  [ 3, 3 ],
  [ 12 ],
  [ 14 ],
  [ 4, new String('c')],
  [ 9 ],
  [ 3, 3 ],
  [ 12 ],
  [ 6 ],
  [ 1 ]
];